// @license
// Copyright (c) Audanika. All Rights Reserved.
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/aud_audio_ui_waveform_version_test.dart.
// coverage:ignore-file

/// The version of the `aud_audio_ui_waveform` package.
const String audAudioUiWaveformVersion = '0.0.1';
